version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  docker-compose:
    build: .
    environment:
      DBServerName: "ms-sql-server, 1433"
      DBName: "platformsdb"
      DBUserID: "sa"
      DBPassword: "pa55w0rd!"
    ports:
      - "8080:80"
